# Generated by Django 4.1.6 on 2023-02-12 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_media',
        ),
        migrations.CreateModel(
            name='QuestionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='question_media/', verbose_name='Question Media')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_media', to='quiz.question')),
            ],
            options={
                'verbose_name': 'Question Media',
                'verbose_name_plural': 'Question Media',
                'ordering': ['id'],
            },
        ),
    ]
